language: python
python:
  - "3.5"

sudo: false

env:
    - TOX_ENV=py35-flake8
    - TOX_ENV=py35-docs
    - TOX_ENV=py35-django1.9

matrix:
  fast_finish: true

install:
  - pip install tox

script:
    - tox -e $TOX_ENV
notifications:
  slack:
    on_success: always
    on_failure: change
    secure: nTedPjRjPYtgB0lhX+NK5rTHx57zxhRLDD8GjrNVf9eJHJ4KaE5UXmQyru02NBNtz8QNDWUdvmouFvI6Nmm94FuY9qyM88MRg1UPiYb5KGDZVwEu5nBE5EUuhB0dKIr0LPbT6lDyqXGbTdR2abYxB5iIvbfzg0pjZrnzNQ42RgbkSWzMRdRcQb/BD/UI82voIChpLGfAnUba0cyy/otTtuC/tci4Z1HiCwqd1xRPJzx7n9Ibcd9SdwQcpDFcaGVJZzFKya8/wYXtlu38rc05bek1gObYrTY8SuAZfuyVbED9+PSfcn6WvFn98Jeq19nHkjlJzUXotFMdLz5q/PBJN+zTrykd/t69JKbW+L1gr4fG7WPBf0jlykGs+CniKpBVm20spwg6RitpmpVDsuQDC4jyp2zpes+yrD9cOUfGxBhkcUOtq1/hhOxtxqy1o+jpFypmALoqXzBGYDS471fYDwiLskGONU76c5xYfjZPJzaYFk7SPNzIT2K9erlSuq2bMhgUG+VRjEpNv+zDMQdXGTkQU7Grvs60M6lhYn8IqtghFaV7VgMO4BUYG3Ay/uS25Q5XQjNFnvLV0t34zvpSDyRy2uCO5Yz8zisxCJo1ix31wS92MnFyEKe+tG26/aDyy9sPX/p34iF2JSZ5ca0UVmvQq/9BBU9yDFOi5arZCHY=
