# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutelary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policyinstanceassign',
            options={'ordering': ['index']},
        ),
        migrations.AlterField(
            model_name='policyinstance',
            name='policy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutelary.Policy'),
        ),
    ]
