# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-04 08:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutelary', '0002_auto_20160304_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyinstance',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tutelary.Role'),
        ),
    ]
