# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-04 14:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutelary', '0003_policyinstance_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policy',
            old_name='body',
            new_name='_body',
        ),
        migrations.RenameField(
            model_name='policyauditlogentry',
            old_name='body',
            new_name='_body',
        ),
    ]
