# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 15:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutelary_example', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parcel',
            options={'ordering': ['status', 'address']},
        ),
        migrations.AlterModelOptions(
            name='party',
            options={'ordering': ['name']},
        ),
    ]
