# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 12:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exampleapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpolicyassignment',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exampleapp.Organisation'),
        ),
        migrations.AlterField(
            model_name='userpolicyassignment',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exampleapp.Project'),
        ),
    ]
